### ISSUE TITLE
Should this recommend elm-verify-examples?

### ISSUE THREAD

**Issue by razzeee** [dillonkearns/idiomatic-elm-package-guide#1]
Might be really useful, but might also confuse some? Not sure.
https://www.npmjs.com/package/elm-verify-examples

**Comment by dillonkearns** [comment]
👍done! https://github.com/dillonkearns/idiomatic-elm-package-guide/commit/dbe1e7a33718ae8b9db3af4f121d9dca74a2fd82

Thanks for the suggestion!
