### ISSUE TITLE
Broken link at License section

### ISSUE THREAD

**Issue by malaire** [dillonkearns/idiomatic-elm-package-guide#3]
In `README.md`, section `### License` following link is broken:

    The [recommended license for Elm projects is BSD3](https://github.com/elm-lang/elm-package#preparing-for-publication).

**Comment by dillonkearns** [comment]
Hello! Thanks for letting me know.

It looks like this no longer appears in the repo that is linked to, so maybe it no longer exists?

We could link to a specific commit in that repo, like https://github.com/elm-lang/elm-package/blob/1a364bccd08f2859f8572d63c2ad5029b6c70ffe/README.md#preparing-for-publication. I'm guessing this document is no longer maintained there. I'm open to other ideas, too, if you have thoughts!

**Comment by malaire** [comment]
The question here is whether BSD3 is still recommended license for Elm projects or not. If yes, then some source should be found for it, if not then that sentence can just be removed.

**Comment by dillonkearns** [comment]
Unfortunately, we may be in an in-between situation.

> The question here is whether BSD3 is still recommended license for Elm projects or not

I'm pretty sure it is.

>  yes, then some source should be found for it

But there may no longer be a source where this is written down formally.

I'll check on Slack to see if anyone has thoughts on this. Thanks for chiming in!

**Comment by dillonkearns** [comment]
Good news! There's now an official comment about this in the Elm compiler repo:

https://github.com/elm/compiler/pull/2091/files

I'll update the link to point there 👍 Thanks for starting the conversation!
